language: python
python:
- '2.7'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_cb425bfbbc9d_key -iv $encrypted_cb425bfbbc9d_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
